on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: Validate jsons

jobs:
  build:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v1
      
      - name: Install R dependencies
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          install.packages("pak", repos = "https://r-lib.github.io/p/pak/dev/")
          pak::local_install_deps()
        shell: Rscript {0}

      - name: Validate jsons
        run: |
          Rscript 'scripts/validate_jsons.R'
