on:
  push:
    paths:
    - 'blogs/**'
  pull_request:
    paths:
    - 'blogs/**'

name: Validate & knit readme

jobs:
  validate:
    runs-on: macOS-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2    
        with:
          fetch-depth: 1
      - uses: r-lib/actions/setup-pandoc@v1
      - uses: r-lib/actions/setup-r@v1
          
      - name: Get changed files
        id: getfile
        run: |
          echo "::set-output name=files::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }}| grep ^blogs | xargs)"
      
      - name: Cleanup json template comments
        run: |
          for f in ${{ steps.getfile.outputs.files }}; do
            echo Cleaning up $f 
            sed -i -e s.//required..g $f
          done

      - name: Install R dependencies
        run: |
          install.packages(c("jsonlite","jsonvalidate", "rmarkdown", "here"), 
                           repos = "https://cloud.r-project.org/")
        shell: Rscript {0}
        
      - name: Validate jsons
        run: Rscript 'scripts/validate_jsons.R'
        
      - name: Render readme files
        if: github.event_name == 'push'
        run: rmarkdown::render("README.Rmd", output_format = "github_document")
        shell: Rscript {0}
        
      - name: Commit data
        if: github.event_name == 'push'
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git commit blogs/ -m 'Commit cleaned jsons' || echo "No changes to commit"
          git commit README.md -m 'Re-knit readme files' || echo "No changes to commit"
          git push origin || echo "Nothin to push"

      
          