on:
  push:
    paths:
    - 'blogs/**'
  pull_request:
    paths:
    - 'blogs/**'

name: Validate jsons

jobs:
  validate:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2    
        with:
          fetch-depth: 0
          
      - name: Get changed files
        id: getfile
        run: |
          echo "::set-output name=files::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }}| grep ^blogs | xargs)"
      
      - name: Cleanup json template comments
        run: |
          for f in ${{ steps.getfile.outputs.files }}; do
            echo Cleaning up $f 
            sed -e s.//required..g $f > tmp
            cat tmp > $f
          done

      - name: Setup R
        uses: r-lib/actions/setup-r@v1

      - name: Install packages
        run: |
          R -e 'install.packages("jsonvalidate")'
          R -e 'install.packages("here")'
      
      - name: Validate jsons
        run: |
          Rscript 'scripts/validate_jsons.R'
          
      - name: Commit cleaned jsons
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git commit blogs/ -m 'Commit cleaned jsons' || echo "No changes to commit"
          git push origin || echo "Nothin to push"
    
  renderreadme:
    needs: validate
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: r-lib/actions/setup-pandoc@v1

      - uses: r-lib/actions/setup-r@v1

      - name: Install R dependencies
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          install.packages(c("jsonlite", "rmarkdown", "here"), repos = "https://cloud.r-project.org/")
        shell: Rscript {0}
        
      - name: Render readme files
        run: rmarkdown::render("README.Rmd", output_format = "github_document")
        shell: Rscript {0}

      - name: Commit results
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git commit README.md -m 'Re-knit readme files' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
      
          